from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol


class SupportsLeague(Protocol):
    async def get_league(self, league_id: str) -> Any: ...
    async def get_rosters(self, league_id: str) -> list[Any]: ...
    async def get_roster(self, league_id: str, roster_id: int) -> Any: ...
    async def get_matchups(self, league_id: str, week: int) -> list[Any]: ...
    async def get_transactions(self, league_id: str, week: int | None = None) -> list[Any]: ...
    async def get_users(self, league_id: str) -> list[Any]: ...
    async def get_nfl_state(self) -> dict[str, Any]: ...


class SupportsPlayers(Protocol):
    async def get_player(self, player_id: str) -> Any: ...
    async def get_players(self, player_ids: list[str]) -> dict[str, Any]: ...
    async def search(self, query: str, limit: int = 20) -> list[Any]: ...
    async def available(self, league_id: str, positions: list[str] | None = None) -> list[Any]: ...
    async def trending(self, kind: str = "add") -> list[Any]: ...


class SupportsProjections(Protocol):
    async def get_projections(
        self, player_ids: list[str], week: int, season: str
    ) -> dict[str, Any]: ...
    async def get_projection(self, player_id: str, week: int, season: str) -> Any: ...


class SupportsNews(Protocol):
    async def get_news(self, player_id: str | None = None) -> list[Any]: ...
    async def get_injuries(self, player_ids: list[str] | None = None) -> list[Any]: ...


class SupportsCache(Protocol):
    async def get(self, key: str) -> Any | None: ...
    async def set(self, key: str, value: Any, ttl: int | None = None) -> None: ...


class SupportsEvents(Protocol):
    async def publish(self, event: Any) -> None: ...


@dataclass
class AnalysisContext:
    league_id: str
    roster_id: int | None
    week: int
    season: str
    league_service: SupportsLeague
    player_service: SupportsPlayers
    projection_service: SupportsProjections
    news_service: SupportsNews
    cache: SupportsCache
    events: SupportsEvents
